name: ClassSystem
version: '${project.version}'
main: classsystem.classsystem.ClassSystem
api-version: 1.18
authors: [ SleepingRaven ]
description: A Class System for my MMORPG
commands:
  fly:
    description: Toggles flight
    usage: /fly
    aliases: [f, flying, toggleflight]
    permission: fly
  god:
    description: Toggles God Mode
    usage: /god
    aliases: [g, godmode, togglegod]
    permission: god
  menu:
    description: Opens the menu!
    usage: /menu
  avatar:
    description: Gives you the ultimate class!
    usage: /avatar
    permission: avatar
  party:
    description: Party invite
    usage: /party [invite/accept/remove/leave/list]
    aliases: [p]
